### ISSUE TITLE
shutdown command error on Ubuntu

### ISSUE THREAD

**Issue by Mondane** [eli-schwartz/calibre-installer#4]
I use your script to update my Calibre, but everytime I start Ubuntu 1604, I get a messagebox showing there was an error. Upon inspection of that error, it turns out to be caused by this command:

`sudo <username> calibre -shutdown-running-calibre`

I believe this command is ran by your script. Do you have a idea how to get rid of this error message?

**Comment by eli-schwartz** [comment]
That is not valid sudo syntax or calibre syntax. The script actually runs `sudo -u <username> calibre --shutdown-running-calibre`.

If that was a copy-paste error, then I am not sure why the command might fail, can you describe how it fails? What does systemd/cron say in the logs? I am not sure what messagebox you are referring to, anyway.

**Comment by Mondane** [comment]
I just reinstalled using your latest script, hopefully the error is gone now.
